beernpike/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('main/', include('main.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import login_view, logout_view, MainView, register, UserUpdateView, WeaponApplicationView, PlacesView, BookView


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),
    path('profile/', UserUpdateView.as_view(), name='user_page'),
    path('weapon-application/', WeaponApplicationView.as_view(), name='application'),
    path('places/<str:location>/', PlacesView.as_view(), name='places'),
    path('book-place/<int:pk>/', BookView.as_view(), name='book'),
    path('', MainView.as_view(), name='home'),
]

app_name = 'main'

products/urls.py
from django.urls import path

from .views import ProductList, add_to_cart, delete_from_cart, CartPage, OrdersPage, make_order, search_view


urlpatterns = [
    path('', ProductList.as_view(), name='products'),
    path('cart/', CartPage.as_view(), name='cart'),
    path('add-to-cart/<int:pk>/', add_to_cart, name='add_product'),
    path('delete-from-cart/<int:pk>/', delete_from_cart, name='delete_from_cart'),
    path('my-orders', OrdersPage.as_view(), name='orders'),
    path('make-order/', make_order, name='do_order'),
    path('search/', search_view, name='search')
]

app_name = 'products'

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from products.models import Product


class RentPlace(models.Model):

    class PlaceChoices(models.TextChoices):
        hunt = 'ht', 'Охота'
        fishing = 'fh', 'Рыбалка'

    class LocationCountries(models.TextChoices):
        russia = 'ru', 'Россия'
        brasil = 'br', 'Бразилия'
        italy = 'it', 'Италия'
        kenia = 'kn', 'Кения'
        new_zeland = 'nz', 'Новая Зеландия'
        zimbabve = 'zb', 'Зимбабве'

    name = models.CharField('Название', max_length=255)
    location = models.CharField('Локация', choices=LocationCountries, max_length=20)
    inhabiants = models.CharField('Обитатели', max_length=511)
    price = models.PositiveIntegerField('Цена', default=0)
    image = models.ImageField('Картинка', upload_to='images/places')
    place_type = models.CharField('Для охоты или рыбалки', choices=PlaceChoices, max_length=10)

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Место'
        verbose_name_plural = 'Места'


class BaseUser(AbstractUser):
    otchestvo = models.CharField('Отчество', max_length=255)
    have_licence = models.BooleanField('Имеет лицензию', default=False)
    buyed_products = models.ManyToManyField(Product, related_name='users_buy')
    cart = models.ManyToManyField(Product, related_name='users_carted')

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class WeaponApplication(models.Model):
    user = models.ForeignKey(BaseUser, on_delete=models.SET_NULL, null=True)
    weapon_type = models.CharField('Тип оружия', max_length=255)
    reason = models.TextField('Причина получения оружия')
    comment = models.TextField('Комметрарий')
    application_date = models.DateTimeField('Дата подачи заявки', auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.weapon_type}"

    class Meta:
        verbose_name = 'Заяка'
        verbose_name_plural = 'Заявки'

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, UserChangeForm

from .models import BaseUser, WeaponApplication


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Имя')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput)

    class Meta:
        model = BaseUser
        fields = ('username', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = UsernameField(label='Имя', widget=forms.TextInput(attrs={"autofocus": True}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = BaseUser
        fields = ('username', 'first_name', 'last_name', 'otchestvo', 'email')


class WeaponForm(forms.ModelForm):

    class Meta:
        model = WeaponApplication
        fields = ('weapon_type', 'reason', 'comment')

main/views.py
from django.db.models.query import QuerySet
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic import View, ListView

from .forms import RegisterForm, LoginForm, CustomUserChangeForm, WeaponForm
from .models import RentPlace

from products.models import Product, RentOrder


User = get_user_model()


class MainView(View):

    def get(self, request):
        context = {
            'products': Product.objects.all()[:5]
        }
        context['ru_count'] = RentPlace.objects.filter(location=RentPlace.LocationCountries.russia).count()
        context['br_count'] = RentPlace.objects.filter(location=RentPlace.LocationCountries.brasil).count()
        context['it_count'] = RentPlace.objects.filter(location=RentPlace.LocationCountries.italy).count()
        context['kn_count'] = RentPlace.objects.filter(location=RentPlace.LocationCountries.kenia).count()
        context['nz_count'] = RentPlace.objects.filter(location=RentPlace.LocationCountries.new_zeland).count()
        context['zb_count'] = RentPlace.objects.filter(location=RentPlace.LocationCountries.zimbabve).count()

        return render(request, 'main/index.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('main:home')


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)

        if form.is_valid():
            print(f'valid form: {form.cleaned_data}')
            user = form.get_user()
            login(request, user)
            return redirect('main:home')
        else:
            print(f'{form.errors}, {form.data}')
            return render(request, 'main/login.html', {'form': form})
    else:
        return render(request, 'main/login.html', {'form': LoginForm()})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('main:home')  # Redirect to a home page or any other page after successful registration
    else:
        form = RegisterForm()

    return render(request, 'main/register.html', {'form': form})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = 'main/user_page.html'
    success_url = reverse_lazy('main:user_page')

    def get_object(self):
        return self.request.user


class WeaponApplicationView(CreateView):
    form_class = WeaponForm
    template_name = 'main/application.html'

    def form_valid(self, form: WeaponForm) -> HttpResponse:
        application = form.save(commit=False)
        application.user = self.request.user
        application.save()

        return redirect('main:home')


class PlacesView(ListView):
    template_name = 'main/places.html'
    context_object_name = 'places'

    def get_queryset(self) -> QuerySet:
        location = self.kwargs['location']

        if location == 'all':
            return RentPlace.objects.all()

        return RentPlace.objects.filter(location=location)


class BookView(View, LoginRequiredMixin):

    def get(self, request, pk):
        try:
            place = RentPlace.objects.get(pk=pk)
        except Exception as e:
            return Http404()
        
        RentOrder.objects.create(
            user=self.request.user,
            place=place
        )

        return redirect('products:orders')

main/templates/main/application.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Заявка на получение оружия</title>
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@500;700;800&amp;family=Big+Shoulders+Text:wght@100;200;400;500;600;700;800;900&amp;family=Epilogue:wght@400;500;600;700&amp;family=Farro:wght@300;400;500;700&amp;family=Inter:wght@200;300;500;600;700;800&amp;family=Josefin+Sans:wght@200;300;400;600;700&amp;family=Merriweather+Sans:wght@300;400;500;600;700;800&amp;family=Poppins:wght@100;200;300;400;500;600;700;800&amp;family=Prompt:wght@100;200;300;400;500;600;700;800&amp;family=Rubik:wght@300;400;500;600;700&amp;family=Shadows+Into+Light&amp;family=Work+Sans:wght@100&amp;display=swap" rel="stylesheet">

    <link href="{% static 'main/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/application.css' %}">

</head>
<body>
    {% include 'main/header.html' %}
    <div class="application-container" style="padding-left: 30px;">
        <form style="padding-top: 30px;" action="{% url 'main:application' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Отправить заявку</button>
        </form>
    </div>
    {% include 'main/footer.html' %}
</body>
</html>

main/templates/main/footer.html
{% load static %}
<footer class="float-start w-100 footer-new" style="margin-top: 0px; min-height: 0px; background-color: white;">
    <div class="container">
       <div class="row row-cols-1 row-cols-lg-3 g-5">
          <div class="col">
            <div class="company-detailso">
               </p>
               <div class="subcribe-siv d-flex align-items-center">
                  <p>chella05andrey@gmail.com</p>
                  <p style="margin-left: 15px;">+79999999999</p>
               </div>
              
            </div>
          </div>
              
              <div class="solint-linst d-flex align-items-center">
                 <a href="https://vk.com/" class="btn"> <img height="30px" width="30px" src="{% static 'main/images/vk.png' %}" class="fab fa-facebook-f"> </a>
                 <a href="https://t.me/piplapsq/" class="btn"> <img height="30px" width="30px" src="{% static 'main/images/telegram.png' %}" class="fab fa-twitter"> </a>
                 <a href="https://t.me/piplapsq/" class="btn"> <img height="30px" width="30px" src="{% static 'main/images/whatsapp.png' %}" class="fab fa-google"> </a>
              </div>
            </div>
          </div>
       </div>
       <hr class="bg-light">
       <div class="d-flex align-items-center justify-content-between">
        <p class="text-center text-white"> © 2024 Медведь и Щука. Все права защищены. </p>
       </div>
       
       
    </div>
  </footer>

main/templates/main/header.html
{% load static %}
<header class="float-start w-100">
    <div class="top-header01">
      
     <nav class="navbar navbar-expand-lg navbar-light">
       <div class="container">
         <a class="navbar-brand" href="{% url 'main:home' %}">
           <img alt="sr" src="{% static 'main/images/logo-m.png' %}" height="100" width="100">
         </a>
         <div class="right-menu-rd d-flex d-lg-none">
 
           <div class="d-flex align-items-center">
             <a data-bs-toggle="modal" data-bs-target="#loginModal" class="btn btn-login">Login</a>
             <a data-bs-toggle="modal" data-bs-target="#registerModal" class="btn btn-partners ms-1 ms-sm-3">Start Free</a>
           </div>
           <button class="navbar-toggler border-0 p-0 ms-2 ms-sm-4 ms-lg-4" type="button" data-bs-toggle="offcanvas" data-bs-target="#mobile-menu">
             <i class="fas fa-bars"></i>
           </button>
         </div>
         
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
             
           
         <li class="nav-item">
             <a class="nav-link" href="{% url 'main:user_page' %}">Мой кабинет</a>
             </li>
 
             <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                   Меню
                 </a>
                 <ul class="dropdown-menu dropdown-menu1">
                  {% if request.user.is_superuser %}
                    <li>
                      <a class="dropdown-item" href="{% url 'admin:index' %}">
                        <span class="imo-icon">
                          <img alt="sr" class="mi-icon" src="{% static 'main/images/admin.png' %}">
                          <img alt="sr" class="mi-icon2" src="{% static 'main/images/admin.png' %}">
                        </span>
                        <span>
                          Админ панель
                        </span>
                        </a>
                    </li>
                  {% endif %}
                   <li>
                     <a class="dropdown-item" href="{% url 'main:application' %}">
                       <span class="imo-icon">
                         <img alt="sr" class="mi-icon" src="{% static 'main/images/8531896.png' %}">
                         <img alt="sr" class="mi-icon2" src="{% static 'main/images/8531896-h.png' %}">
                       </span>
                       <span>
                          Заявка на оружее
                       </span>
                       </a>
                   </li>
   
                 </ul>
             </li>

             <li class="nav-item">
                 <a class="nav-link" href="{% url 'products:orders' %}">Мои покупки</a>
             </li>
 
             <li class="nav-item">
                 <a class="nav-link" href="{% url 'products:products' %}">Товары</a>
             </li>
            
           </ul>
           <form class="d-flex ms-3" method="GET" action="{% url 'products:search' %}">
              <input class="form-control me-2 search-input" type="search" placeholder="Поиск товаров" aria-label="Search" name="q">
              <button class="btn btn-outline-success" type="submit">Поиск</button>
           </form>

         </div>
 
         
         <div class="right-menu-rd d-none d-lg-block">
             <ul class="solinu-links d-flex align-items-center">
                 <li class="dropdown position-relative ms-3">
                    <button onclick="window.location.href = '{% url 'products:cart' %}'" class="btn comon-top-right-a" type="button" data-bs-toggle="dropdown">
                        <span class="icouj">
                          <img alt="sy" src="{% static 'main/images/2169842.png' %}">
                        </span>
                        {% if request.user.is_authenticated %}
                          <span class="nubn">{{ request.user.cart.count }}</span>
                        {% endif %}
                    </button>

                 </li>
                  {% if request.user.is_authenticated %}
                      <li>
                          <a href="{% url 'main:logout' %}" class="btn comon-top-right-a ms-2">
                          <span class="icouj">
                              <img alt="sy" src="{% static 'main/images/exit.png' %}">
                          </span>
                          </a>                 
                      </li>
                  {% else %}
                      <li>
                          <a href="{% url 'main:login' %}" class="btn comon-top-right-a ms-2">
                          <span class="icouj">
                              <img alt="sy" src="{% static 'main/images/9706624.png' %}">
                          </span>
                          </a>                 
                      </li>
                  {% endif %}
                 <li>
                   <a href="{% url 'main:places' 'all' %}" class="btn btn-partners ms-2">Забронируй свою охоту</a>
                 </li>

               
             </ul>
         </div>
 
       </div>
     </nav>
       
    </div>
  
 </header>

main/templates/main/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet", type="text/css" href="{% static 'main/css/log_reg.css' %}">

    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@500;700;800&amp;family=Big+Shoulders+Text:wght@100;200;400;500;600;700;800;900&amp;family=Epilogue:wght@400;500;600;700&amp;family=Farro:wght@300;400;500;700&amp;family=Inter:wght@200;300;500;600;700;800&amp;family=Josefin+Sans:wght@200;300;400;600;700&amp;family=Merriweather+Sans:wght@300;400;500;600;700;800&amp;family=Poppins:wght@100;200;300;400;500;600;700;800&amp;family=Prompt:wght@100;200;300;400;500;600;700;800&amp;family=Rubik:wght@300;400;500;600;700&amp;family=Shadows+Into+Light&amp;family=Work+Sans:wght@100&amp;display=swap" rel="stylesheet">

    <link href="{% static 'main/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">

    <title>Вход в систему</title>
</head>
<body style="background-color: rgb(11, 231, 11);">

{% include 'main/header.html' %}

<div class="login-page">
    <div class="form">
        <form class="login-form" action="{% url 'main:login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
        <p class="message">Не зарегистрированы? <a href="{% url 'main:register' %}">Создайте аккаунт</a></p>
        </form>
    </div>
</div>
{% include 'main/footer.html' %}

<style>
.login-page {
    display: flex;
    align-items: center;
    justify-content: center;
}
</style>

</body>
</html>

main/templates/main/places.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Места для рыбалки/охоты в {{ places.0.location }}</title>
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@500;700;800&amp;family=Big+Shoulders+Text:wght@100;200;400;500;600;700;800;900&amp;family=Epilogue:wght@400;500;600;700&amp;family=Farro:wght@300;400;500;700&amp;family=Inter:wght@200;300;500;600;700;800&amp;family=Josefin+Sans:wght@200;300;400;600;700&amp;family=Merriweather+Sans:wght@300;400;500;600;700;800&amp;family=Poppins:wght@100;200;300;400;500;600;700;800&amp;family=Prompt:wght@100;200;300;400;500;600;700;800&amp;family=Rubik:wght@300;400;500;600;700&amp;family=Shadows+Into+Light&amp;family=Work+Sans:wght@100&amp;display=swap" rel="stylesheet">

    <link href="{% static 'main/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/places.css' %}">

</head>
<body>

<div class="root">
    {% include 'main/header.html' %}

    <div class="container-places">
        {% for place in places %}
            <div class="fishing-place">
                <img src="{{ place.image.url }}" class="fishing-place-image">
                <div class="fishing-place-details">
                    <h2>{{ place.name }}</h2>
                    <p><strong>Цена за бронирование:</strong> {{ place.price }} руб.</p>
                    <p><strong>Описание:</strong> {{ place.location }}</p>
                    <p><strong>Тип места:</strong> {{ place.place_type }}</p>
                    <p><strong>Обитатели:</strong> {{ place.inhabiants }}</p>
                    <a href="{% url 'main:book' pk=place.id %}" class="rent-button">Арендовать это место</a>
                </div>
            </div>
        {% endfor %}
    </div>

    {% include 'main/footer.html' %}
</div>

</body>
</html>

main/templates/main/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet", type="text/css" href="{% static 'main/css/log_reg.css' %}">

    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@500;700;800&amp;family=Big+Shoulders+Text:wght@100;200;400;500;600;700;800;900&amp;family=Epilogue:wght@400;500;600;700&amp;family=Farro:wght@300;400;500;700&amp;family=Inter:wght@200;300;500;600;700;800&amp;family=Josefin+Sans:wght@200;300;400;600;700&amp;family=Merriweather+Sans:wght@300;400;500;600;700;800&amp;family=Poppins:wght@100;200;300;400;500;600;700;800&amp;family=Prompt:wght@100;200;300;400;500;600;700;800&amp;family=Rubik:wght@300;400;500;600;700&amp;family=Shadows+Into+Light&amp;family=Work+Sans:wght@100&amp;display=swap" rel="stylesheet">

    <link href="{% static 'main/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">

    <title>Регистрация</title>
</head>
<body style="background-color: rgb(11, 231, 11);">

{% include 'main/header.html' %}

<div class="login-page" style="margin-top: 40px;">
    <div class="form">
        <form class="login-form" action="{% url 'main:register' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Зарегистрироваться</button>
            <p class="message">Уже зарегистированы? <a href="{% url 'main:login' %}">Войдите</a></p>
        </form>
    </div>
</div>
{% include 'main/footer.html' %}

<style>
    .login-page {
        display: flex;
        align-items: center;
        justify-content: center;
    }
</style>

</body>
</html>

main/templates/main/user_page.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Личный кабинет {{ request.user.username }}</title>
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@500;700;800&amp;family=Big+Shoulders+Text:wght@100;200;400;500;600;700;800;900&amp;family=Epilogue:wght@400;500;600;700&amp;family=Farro:wght@300;400;500;700&amp;family=Inter:wght@200;300;500;600;700;800&amp;family=Josefin+Sans:wght@200;300;400;600;700&amp;family=Merriweather+Sans:wght@300;400;500;600;700;800&amp;family=Poppins:wght@100;200;300;400;500;600;700;800&amp;family=Prompt:wght@100;200;300;400;500;600;700;800&amp;family=Rubik:wght@300;400;500;600;700&amp;family=Shadows+Into+Light&amp;family=Work+Sans:wght@100&amp;display=swap" rel="stylesheet">

    <link href="{% static 'main/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/user_page.css' %}">

</head>
<body>
    {% include 'main/header.html' %}
    <div class="container-user">
        <aside class="sidebar">
            <div class="user-info">
                <h2>Информация о пользователе</h2>
                <p><strong>Имя пользователя:</strong> {{ request.user.username }}</p>
                {% if request.user.first_name %}<p><strong>Имя:</strong> {{ request.user.first_name }}</p>{% endif %}
                {% if request.user.last_name %}<p><strong>Фамилия:</strong> {{ request.user.last_name }}</p>{% endif %}
                {% if request.user.otchestvo %}<p><strong>Отчество:</strong> {{ request.user.otchestvo }}</p>{% endif %}
                {% if request.user.email %}<p><strong>Email:</strong> {{ request.user.email }}</p>{% endif %}
            </div>
        </aside>
        <main class="content">
            <h2>Изменение данных пользователя</h2>
            <form class="user-form" action="{% url 'main:user_page' %}" method="post">
                {% csrf_token %}
                {{ form.as_div }}
                <button type="submit">Сохранить изменения</button>
            </form>
        </main>
    </div>
    {% include 'main/footer.html' %}
</body>

<script>
let password = document.querySelector('div[id="id_password_helptext"]')
password.parentElement.remove()
</script>

</html>