beernpike/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('main/', include('main.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import login_view, logout_view, MainView, register, UserUpdateView, WeaponApplicationView, PlacesView, BookView


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),
    path('profile/', UserUpdateView.as_view(), name='user_page'),
    path('weapon-application/', WeaponApplicationView.as_view(), name='application'),
    path('places/<str:location>/', PlacesView.as_view(), name='places'),
    path('book-place/<int:pk>/', BookView.as_view(), name='book'),
    path('', MainView.as_view(), name='home'),
]

app_name = 'main'

products/urls.py
from django.urls import path

from .views import ProductList, add_to_cart, delete_from_cart, CartPage, OrdersPage, make_order, search_view


urlpatterns = [
    path('', ProductList.as_view(), name='products'),
    path('cart/', CartPage.as_view(), name='cart'),
    path('add-to-cart/<int:pk>/', add_to_cart, name='add_product'),
    path('delete-from-cart/<int:pk>/', delete_from_cart, name='delete_from_cart'),
    path('my-orders', OrdersPage.as_view(), name='orders'),
    path('make-order/', make_order, name='do_order'),
    path('search/', search_view, name='search')
]

app_name = 'products'

products/models.py
from django.db import models


class Product(models.Model):

    class ColorChoices(models.TextChoices):
        red = 'red', 'Красный'
        green = 'green', 'Зелёный'
        blue = 'blue', 'Синий'
        yellow = 'yellow', 'Жёлтый'
        black = 'black', 'Чёрный'

    name = models.CharField('Имя', max_length=255)
    price = models.PositiveIntegerField('Цена', default=0)
    desc = models.TextField('Описание')
    color = models.CharField('Цвет', max_length=255, choices=ColorChoices)
    producer_country = models.CharField('Старана производитель', max_length=255)
    image = models.ImageField('Картинка', upload_to='images/')

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Order(models.Model):
    user = models.ForeignKey('main.BaseUser', on_delete=models.SET_NULL, null=True)
    products = models.ManyToManyField(Product, related_name='orders')
    datetime_made = models.DateTimeField('Время заказа', auto_now=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class RentOrder(models.Model):
    user = models.ForeignKey('main.BaseUser', on_delete=models.SET_NULL, null=True)
    place = models.ForeignKey('main.RentPlace', on_delete=models.SET_NULL, null=True)
    datetime_made = models.DateTimeField('Время заказа', auto_now=True)

    class Meta:
        verbose_name = 'Заказ оренды'
        verbose_name_plural = 'Заказы оренды'

products/views.py
from typing import Any

from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.db import models
from django.http import HttpResponse
from django.db.models.aggregates import Sum

from .models import Product, Order, RentOrder


class ProductList(ListView):
    template_name = 'products/products.html'
    queryset = Product.objects.all()
    context_object_name = 'products'


def add_to_cart(request, pk: int):
    product = Product.objects.get(pk=pk)

    if request.user.is_authenticated:
        request.user.cart.add(product)
        request.user.save()

        return redirect('products:cart')
    else:
        return redirect('main:login')


def delete_from_cart(request, pk: int):
    product = Product.objects.get(pk=pk)

    if request.user.is_authenticated:
        request.user.cart.remove(product)
        request.user.save()

        return redirect('products:cart')
    else:
        return redirect('main:home')


class CartPage(ListView):
    context_object_name = 'products'
    template_name = 'products/cart.html'

    def get_queryset(self) -> models.QuerySet[Any]:
        if self.request.user.is_authenticated:
            return self.request.user.cart.all()
        else:
            return None


class OrdersPage(ListView):
    context_object_name = 'orders'
    template_name = 'products/orders.html'

    def get_queryset(self) -> models.QuerySet[Any]:
        if self.request.user.is_authenticated:
            return Order.objects.filter(user=self.request.user).annotate(total_price=Sum('products__price'))
        else:
            return None
        
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['places'] = RentOrder.objects.filter(user=self.request.user)

        return context


def make_order(request):
    if request.user.is_authenticated:
        cart_products = request.user.cart.all()

        if len(cart_products) == 0:
            return redirect('products:cart')
        
        order = Order.objects.create(user=request.user)
        order.products.add(*cart_products)
        order.save()

        return redirect('products:orders')
    else:
        return HttpResponse('Unauthtorized', status=401)


def search_view(request):
    query = request.GET.get('q')
    products = Product.objects.filter(name__regex=r'(?i){}'.format(query)) if query else []

    return render(request, 'products/products.html', {'products': products})

products/templates/products/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Корзина</title>
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@500;700;800&amp;family=Big+Shoulders+Text:wght@100;200;400;500;600;700;800;900&amp;family=Epilogue:wght@400;500;600;700&amp;family=Farro:wght@300;400;500;700&amp;family=Inter:wght@200;300;500;600;700;800&amp;family=Josefin+Sans:wght@200;300;400;600;700&amp;family=Merriweather+Sans:wght@300;400;500;600;700;800&amp;family=Poppins:wght@100;200;300;400;500;600;700;800&amp;family=Prompt:wght@100;200;300;400;500;600;700;800&amp;family=Rubik:wght@300;400;500;600;700&amp;family=Shadows+Into+Light&amp;family=Work+Sans:wght@100&amp;display=swap" rel="stylesheet">

    <link href="{% static 'main/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'products/css/cart.css' %}">
</head>
<body>

<div class="page" style="display: flex; flex-direction: column; min-height: 100vh; justify-content: space-between;">
    {% include 'main/header.html' %}

    {% if products %}
        <div class="favorites-block high-element" style="width: 95vw;">
            <div class="favorites-list">
                <div class="favorites-controls">
                    <div class="default-checkbox">
                        <input type="checkbox" checked class="default-checkbox" id="select-all-checkbox">
                        <label for="select-all-checkbox">Выбрать все</label>
                    </div>
                    <div class="delete-button" id="delete-all-button">
                        <img src="{% static 'products/images/x.png' %}" class="delete-icon">
                        <span class="delete-button-text">Удалить все</span>
                    </div>
                </div>

                <div class="favorites">
                    {% for product in products %}
                        <div style="border-color: black; border: 1px solid;" class="favorite" data-objectid="{{ product.pk }}">
                            <div><img class="favorite-img letter-img" src="{{ product.image.url }}"></div>
                            <div class="favorite-content">
                                <div class="favorite-content-text">
                                    <span>{{ product.name }}</span>
                                    <span class="second-favorite-text">{{ product.desc }}</span>
                                </div>
                                <div class="favorite-el-controls">
                                    <div class="default-checkbox">
                                        <input type="checkbox" checked name="letter-checkbox" id="letter-checkbox{{ product.pk }}">
                                        <label for="letter-checkbox{{ product.pk }}"></label>
                                    </div>
                                    <div class="delete-button delete-favorite">
                                        <img src="{% static 'products/images/x.png' %}" class="delete-icon">
                                        <a href="{% url 'products:delete_from_cart' pk=product.pk %}" class="delete-button-text">Удалить</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="select-all">
                <div class="select-all-container">
                    <button onclick="window.location.href = '{% url 'products:do_order' %}'" class="default-button select-all-button">Заказать</button>
                </div>
            </div>
        </div>
    {% else %}
        <div class="empty-text-container">
            <div class="empty-objects-text block-container">
                <img src="{% static 'products/images/delbox.png' %}" style="height: 100px; width: 100px; margin-top: 100px; margin-left: 600px;">
                <p style="text-align: center; margin-top: 20px;">
                    Вам нужно войти и выбрать продукты, чтобы они появились в корзине
                </p>
            </div>
        </div>
    {% endif %}

    {% include 'main/footer.html' %}

</div>

<script src="{% static 'products/js/cart.js' %}"></script>

</body>
</html>

products/templates/products/orders.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список покупок</title>
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@500;700;800&amp;family=Big+Shoulders+Text:wght@100;200;400;500;600;700;800;900&amp;family=Epilogue:wght@400;500;600;700&amp;family=Farro:wght@300;400;500;700&amp;family=Inter:wght@200;300;500;600;700;800&amp;family=Josefin+Sans:wght@200;300;400;600;700&amp;family=Merriweather+Sans:wght@300;400;500;600;700;800&amp;family=Poppins:wght@100;200;300;400;500;600;700;800&amp;family=Prompt:wght@100;200;300;400;500;600;700;800&amp;family=Rubik:wght@300;400;500;600;700&amp;family=Shadows+Into+Light&amp;family=Work+Sans:wght@100&amp;display=swap" rel="stylesheet">

    <link href="{% static 'main/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'products/css/orders.css' %}">
</head>

<body>
    <div style="display: flex; flex-direction: column; justify-content: space-between; align-items: center; min-height: 100vh;">
        {% include 'main/header.html' %}

        <main style="width: 95vw;">
            {% if orders or places %}
                {% for order in orders %}
                    <div class="order">
                        <div class="order-header">
                            <span class="order-date">{{ order.datetime_made|date:"d E Y, H:i" }}</span>
                            <span class="order-total">Сумма: {{ order.total_price }} руб.</span>
                        </div>
                        <div class="order-items">
                            <p>Товары в заказе:</p>
                            {% for product in order.products.all %}
                                <p><strong>{{ product.name }}</strong></p>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}

                {% for place in places %}
                    <div class="order">
                        <div class="order-header">
                            <span class="order-date">{{ place.datetime_made|date:"d E Y, H:i" }}</span>
                            <span class="order-total">Сумма: {{ place.place.price }} руб.</span>
                        </div>
                        <div class="order-items">
                            <p>Тип места:</p>
                            <p><strong>{{ place.place.place_type }}</strong></p>
                        </div>
                        <div class="order-items">
                            <p>Обитатели:</p>
                            <p><strong>{{ place.place.inhabiants }}</strong></p>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="no-orders">
                    <img src="{% static 'products/images/delbox.png' %}" alt="No orders" class="no-orders-image">
                    <p class="no-orders-text">Вы не авторизованы или у вас ещё нет заказов.</p>
                </div>
            {% endif %}
        </main>

        {% include 'main/footer.html' %}
    </div>
</body>
</html>

products/templates/products/products.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список товаров</title>
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@500;700;800&amp;family=Big+Shoulders+Text:wght@100;200;400;500;600;700;800;900&amp;family=Epilogue:wght@400;500;600;700&amp;family=Farro:wght@300;400;500;700&amp;family=Inter:wght@200;300;500;600;700;800&amp;family=Josefin+Sans:wght@200;300;400;600;700&amp;family=Merriweather+Sans:wght@300;400;500;600;700;800&amp;family=Poppins:wght@100;200;300;400;500;600;700;800&amp;family=Prompt:wght@100;200;300;400;500;600;700;800&amp;family=Rubik:wght@300;400;500;600;700&amp;family=Shadows+Into+Light&amp;family=Work+Sans:wght@100&amp;display=swap" rel="stylesheet">

    <link href="{% static 'main/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'products/css/products.css' %}">
</head>
<body>
    {% include 'main/header.html' %}
    <main>
        <section class="product-list">
            {% for product in products %}
                <div class="product-card">
                    <img src="{{ product.image.url }}" alt="Товар 1">
                    <h2>{{ product.name }}</h2>
                    <p class="price">{{ product.price }}₽</p>
                    <p class="description">{{ product.desc }}</p>
                    <button onclick="window.location.href = '{% url 'products:add_product' product.pk %}'" class="add-to-cart">Добавить в корзину</button>
                </div>
            {% endfor %}
        </section>
    </main>
</body>


<script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'main/js/jquery.min.js' %}"></script>
<script src="{% static 'main/js/custom.js' %}"></script>
<script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'products/js/commons.js' %}"></script>
<script src="{% static 'products/js/demo.js' %}"></script>



{% include 'main/footer.html' %}

</html>